# This is a basic workflow to help you get started with Actions

name: CI - Build signed apk for testing

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the specified branch
  push:
    branches: [ mpv ]
  pull_request:
    branches: [ mpv ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Generate Release APK
        run: ./gradlew assembleRelease
      
      - name: Sign APK
        uses: r0adkll/sign-android-release@v1
        # ID used to access action output
        id: sign_app
        with:
          releaseDirectory: app/proprietary/debug
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
      
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
        
      - name: Rename APK
        id: rename
        run: mv ${{steps.sign_app.outputs.signedReleaseFile}} app/proprietary/debug/jellyfin-android-mpv-${{ steps.date.outputs.date }}.apk
        
      - name: Publish Release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: testing-${{ steps.date.outputs.date }}
          prerelease: true
          title: "Testing Build"
          files: |
            app/proprietary/debug/jellyfin-android-mpv-${{ steps.date.outputs.date }}.apk
